### ISSUE TITLE
Container.getSlot(Container.java:109).

### ISSUE THREAD

**Issue by HanielCota** [hpfxd/PandaSpigot#144] opened 2023-05-25 23:50 UTC
I just caught click with button that defends in minecraft

[20:47:30 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 49, Size: 45
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_312]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:12) ~[patched_1.8.8.jar:git-PandaSpigot-"098345f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:881) ~[patched_1.8.8.jar:git-PandaSpigot-"098345f"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.jar:git-PandaSpigot-"098345f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:815) ~[patched_1.8.8.jar:git-PandaSpigot-"098345f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) ~[patched_1.8.8.jar:git-PandaSpigot-"098345f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-"098345f"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.IndexOutOfBoundsException: Index: 49, Size: 45
        at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_312]
        at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_312]
        at net.minecraft.server.v1_8_R3.Container.getSlot(Container.java:109) ~[patched_1.8.8.jar:git-PandaSpigot-"098345f"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1732) ~[patched_1.8.8.jar:git-PandaSpigot-"098345f"]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:17) ~[patched_1.8.8.jar:git-PandaSpigot-"098345f"]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:5) ~[patched_1.8.8.jar:git-PandaSpigot-"098345f"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(PlayerConnectionUtils.java:9) ~[patched_1.8.8.jar:git-PandaSpigot-"098345f"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:11) ~[patched_1.8.8.jar:git-PandaSpigot-"098345f"]

**Comment by andreasdc** [comment] 2023-05-26 08:26
By the way it could be optimized
![image](https://github.com/hpfxd/PandaSpigot/assets/82218780/fddf9ba0-c256-40fe-920b-45401631a020)

**Comment by HanielCota** [comment] 2023-05-26 15:15
> A propósito, poderia ser otimizado ![imagem](https://user-images.githubusercontent.com/82218780/241163445-fddf9ba0-c256-40fe-920b-45401631a020.png)

Where is this print from?

**Comment by andreasdc** [comment] 2023-05-26 15:44
Spark

**Comment by HanielCota** [comment] 2023-06-18 12:49
Ward

**Comment by HanielCota** [comment] 2023-07-09 17:59
Fix?

**Comment by andreasdc** [comment] 2023-07-09 18:00
Way to reproduce?

**Comment by jose27iwnl** [comment] 2023-07-12 10:00
Can u please provide the code
And a full log?

**Comment by andreasdc** [comment] 2023-07-13 16:03
What fix?

**Comment by HanielCota** [comment] 2023-07-13 16:04
// PandaSpigot start - Fix IndexOutOfBoundsException from Container

    public Slot getSlot(int i) {
        if (i >= 0 && i < this.c.size()) {
            return (Slot) this.c.get(i);
        }
        return null;
    }
    // PandaSpigot end


    public ItemStack b(EntityHuman entityhuman, int i) {
        Slot slot = (Slot) this.c.get(i);

        return slot != null ? slot.getItem() : null;
    }

Line 109

net.minecraft

**Comment by jose27iwnl** [comment] 2023-07-13 17:41
> I had made the fix and sent it to Ryan but he didn't put it here...

Can you provide the code u used when it gave you the error?

**Comment by HanielCota** [comment] 2023-07-13 17:57
It was vanilla and just opened a chest in the game

**Comment by andreasdc** [comment] 2023-07-13 17:59
> It was vanilla and just opened a chest in the game

How to reproduce it?

**Comment by HanielCota** [comment] 2023-07-13 18:02
As I said, I just downloaded the last jar and went to start developing things for version 1.8, but then I had to create a design, so I took items from the creative and put them in the trunk so I could have an idea of ​​how the menu would be made, apart from that it was all vanilla and there was no code it was 0 plugins

**Comment by uRyanxD** [comment] 2023-10-06 15:08
Closing this issue due to being unable to reproduce and no other cases reported.

**Closed by uRyanxD** 2023-10-06 15:08 UTC
