### ISSUE TITLE
Protection stones error

### ISSUE THREAD

**Issue by elpersas** [hpfxd/PandaSpigot#46] opened 2022-11-21 06:23 UTC
The fork is awesome but plugin compatibility is bad,do you have discord?

**Comment by andreasdc** [comment] 2022-11-21 14:44
What is not compatible?

**Comment by mechoriet** [comment] 2022-11-21 19:51
We need to have more information like a error log or crashlog so we could replicate it

**Comment by uRyanxD** [comment] 2022-12-01 18:13
I tested the version of this plugin recommended for 1.8 - 1.12 but it doesn't work because of the WorldGuard version, it was probably done using WorldGuard from 1.13, so if this issue is because of this error, it's not PandaSpigot's fault

Error:
[15:07:50 ERROR]: Error occurred while enabling ProtectionStones v2.7.6pre1.13 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/registry/FlagConflictException
        at dev.espi.protectionstones.ProtectionStones.onEnable(ProtectionStones.java:424) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PandaSpigot-71]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) ~[patched_1.8.8.jar:git-PandaSpigot-71]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:445) ~[patched_1.8.8.jar:git-PandaSpigot-71]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) ~[patched_1.8.8.jar:git-PandaSpigot-71]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) ~[patched_1.8.8.jar:git-PandaSpigot-71]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:439) ~[patched_1.8.8.jar:git-PandaSpigot-71]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:403) ~[patched_1.8.8.jar:git-PandaSpigot-71]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:358) ~[patched_1.8.8.jar:git-PandaSpigot-71]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:301) ~[patched_1.8.8.jar:git-PandaSpigot-71]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:603) ~[patched_1.8.8.jar:git-PandaSpigot-71]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-71]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.flags.registry.FlagConflictException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_352]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PandaSpigot-71]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PandaSpigot-71]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_352]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_352]
        ... 13 more

**Comment by uRyanxD** [comment] 2023-04-15 15:15
I am closing this issue due to not getting response from the author about the issue

**Closed by uRyanxD** 2023-04-15 15:15 UTC
