### ISSUE TITLE
Kick problem

### ISSUE THREAD

**Issue by haroldrc** [hpfxd/PandaSpigot#94] opened 2023-02-07 10:16 UTC
Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/75 (ClientboundSetChunkCacheCenterPacket) was larger than I expected, found 51 bytes extra whilst reading packet 75

it happens when i restart the server, if i try to login a second time it doesn't kick me out

**Comment by uRyanxD** [comment] 2023-02-13 16:37
Duplicate of #52

**Closed** 2023-02-18 10:26 UTC
