### ISSUE TITLE
Irregular crashes: Exception ticking world entities

### ISSUE THREAD

**Issue by Packsolite** [hpfxd/PandaSpigot#22] opened 2022-06-28 13:01 UTC
PandaSpigot crashes every now and then (quite rarely, but it does happen) with the following exception:
[crashlog.txt](https://github.com/hpfxd/PandaSpigot/files/9001234/crashlog.txt)

Not sure what triggers it, it seems to be randomly?

Latest version f151e5a60ae036e29dafb1a9d11ef157cdb56ac6

Configuration:
[pandaspigot.yml.txt](https://github.com/hpfxd/PandaSpigot/files/9001259/pandaspigot.yml.txt)
[paper.yml.txt](https://github.com/hpfxd/PandaSpigot/files/9001261/paper.yml.txt)

**Comment by uRyanxD** [comment] 2022-07-01 01:09
Can you share your plugin list?

**Comment by Packsolite** [comment] 2022-07-01 16:33
> Can you share your plugin list?

Sure, but it probably won't help much as most of the plugins are in made in house. Here are the ones publicly available:
- ViaVersion 4.3.2
- MultiverseCores 2.4-b527
- CloudnetBridge 
- spark
- LuckPerms

**Comment by uRyanxD** [comment] 2022-10-21 15:00
If I remember correctly, TileEntity errors are caused by corrupt entities, Paper added an option to remove corrupt entities, please see if "remove-invalid-mob-spawner-tile-entities" option is enabled in paper.yml

**Comment by Packsolite** [comment] 2022-10-22 12:06
> If I remember correctly, this error are caused by corrupt entities, Paper added an option to remove corrupt entities, please see if "remove-invalid-mob-spawner-tile-entities" option is enabled in paper.yml

The paper config is attached in the first post.
`remove-invalid-mob-spawner-tile-entities` is set to `true`, so thats not the issue sadly :/

**Comment by uRyanxD** [comment] 2023-04-15 15:19
I'm closing this issue due to not getting a new reply from the author

**Closed by uRyanxD** 2023-04-15 15:19 UTC
