### ISSUE TITLE
Banning players worked before PandaSpigot, but broke after switching to a different software.

### ISSUE THREAD

**Issue by legendcuzican13** [hpfxd/PandaSpigot#106] opened 2023-03-31 20:02 UTC
Prior to using PandaSpigot, banning players using /ban worked perfectly fine. Now after using PandaSpigot, /ban simply kicks the player. I checked this by switching back to FlamePaper, and saw that bans were working fine. There aren't any console errors either.

**Comment by uRyanxD** [comment] 2023-04-15 18:02
I couldn't reproduce, I removed my op and banned myself, I was blocked from joining the server

**Comment by legendcuzican13** [comment] 2023-04-15 22:31
Alright

**Comment by legendcuzican13** [comment] 2023-04-15 22:31
Imma close this as I fixed the issue by using the advanced ban plugin. Alternatively you could probably use blobs solution to fix it too though I haven't tested that.

**Comment by mechoriet** [comment] 2023-05-25 16:51
@uRyanxD can you try with this build: 
[pandaspigot-test.zip](https://github.com/hpfxd/PandaSpigot/files/11567352/pandaspigot-test.zip)

I believe I've found the root cause that causes this with not launching non listened events
if that was it then we have to do something else with maybe a toggle to force unlistened to process

**Comment by uRyanxD** [comment] 2023-06-18 13:26
Fixed in [e933295](https://github.com/hpfxd/PandaSpigot/commit/e933295bbace5c16ae35afe9d9d3b7b63f615cb2)

**Closed** 2023-06-18 13:26 UTC
Labels: bug, confirmed
