### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Ancienty** [hpfxd/PandaSpigot#152] opened 2023-07-12 00:55 UTC
Hello,

I don't know if I'm supposed to submit this as an error, I just switched to Panda and I don't really know if this is caused by PandaSpigot.
However the output on the console said I should report it, so here I am.

Sorry in advance if I shouldn't have submitted this issue.

```
[03:49:41] [Craft Scheduler Thread - 441/WARN]: Exception in thread "Craft Scheduler Thread - 441" 
[03:49:41] [Craft Scheduler Thread - 441/WARN]: org.apache.commons.lang.UnhandledException: Plugin CombatLog v1.8.11-hack generated an exception while executing task 75
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:823)
Caused by: java.lang.NoSuchMethodError: org/bukkit/Server.getOnlinePlayers()[Lorg/bukkit/entity/Player; (loaded from file:/root/Skyblock/cache/patched_1.8.8.jar by sun.misc.Launcher$AppClassLoader@9a664ecd) called from class com.jackproehl.plugins.Metrics (loaded from file:/root/Skyblock/plugins/CombatLog-1.8.11-fix.jar by org.bukkit.plugin.java.PluginClassLoader@bd2b491c).
	at com.jackproehl.plugins.Metrics.postPlugin(Metrics.java:192)
	at com.jackproehl.plugins.Metrics.access$4(Metrics.java:186)
	at com.jackproehl.plugins.Metrics$1.run(Metrics.java:119)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more

[03:49:43] [Async Chat Thread - #23/INFO]: 6.16K ┃ YETKILI vanks47 ► her gün kravat takıyoruz bavulla okula gidiyorduk
[03:49:46] [Async Chat Thread - #23/INFO]: 6.16K ┃ YETKILI vanks47 ► sıcağın baharında
[03:49:50] [Async Chat Thread - #23/INFO]: 6.16K ┃ YETKILI vanks47 ► pilot gibi
[03:50:54] [PandaSpigot Watchdog Thread/ERROR]: The server has stopped responding!
[03:50:54] [PandaSpigot Watchdog Thread/ERROR]: Please report this in https://github.com/hpfxd/PandaSpigot/issues!
[03:50:54] [PandaSpigot Watchdog Thread/ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
[03:50:54] [PandaSpigot Watchdog Thread/ERROR]: PandaSpigot version: git-PandaSpigot-111 (MC: 1.8.8)
[03:50:54] [PandaSpigot Watchdog Thread/ERROR]: ------------------------------
[03:50:54] [PandaSpigot Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to PandaSpigot!):
```

Also I've attached a javacore file, don't know what that is but it was created after this crash. Feel free to check that out as well.
[javacore.20230712.034951.1063699.0002.txt](https://github.com/hpfxd/PandaSpigot/files/12022552/javacore.20230712.034951.1063699.0002.txt)

**Comment by MachineBreaker** [comment] 2023-07-12 01:20
Send the entire watchdog thread dump

**Comment by Ancienty** [comment] 2023-07-12 01:42
Here you go:
[log.txt](https://github.com/hpfxd/PandaSpigot/files/12022852/log.txt)

**Comment by jose27iwnl** [comment] 2023-07-12 09:43
It seems the same issue with metrics of multiverse core
As uRyanXD_ said on discord
It seems they are using legacy mappings
It still works, just throws the error.

**Comment by jose27iwnl** [comment] 2023-07-12 10:09
> > Here you go: [log.txt](https://github.com/hpfxd/PandaSpigot/files/12022852/log.txt)
> 
> DecentHolograms caused a deadlock

U are a machine 🫡

**Comment by Ancienty** [comment] 2023-07-12 12:13
> > Here you go: [log.txt](https://github.com/hpfxd/PandaSpigot/files/12022852/log.txt)
> 
> DecentHolograms caused a deadlock

Is this somehow related to Panda? I used to use Paper || FlamePaper and didn't have this issue.
If it's not related to Panda, what could I do to prevent this? Stop using DecentHolograms all together?

**Comment by MachineBreaker** [comment] 2023-07-12 12:34
> > > Here you go: [log.txt](https://github.com/hpfxd/PandaSpigot/files/12022852/log.txt)
> > 
> > 
> > DecentHolograms caused a deadlock
> 
> Is this somehow related to Panda? I used to use Paper || FlamePaper and didn't have this issue. If it's not related to Panda, what could I do to prevent this? Stop using DecentHolograms all together?

Report it to the DecentHolograms issue tracker

**Comment by Ancienty** [comment] 2023-07-15 11:16
[latest.log](https://github.com/hpfxd/PandaSpigot/files/12061228/latest.log)

The crash is probably related to DecentHolograms again but I was wondering if the errors that Essentials is throwing are related to Panda or not?

**Comment by uRyanxD** [comment] 2023-07-15 16:30
Caused by: java.lang.NoSuchMethodError: org/bukkit/block/BlockState.getBlockData()Lorg/bukkit/block/data/BlockData;

BlockData only exists in Bukkit 1.13+

**Comment by uRyanxD** [comment] 2023-08-13 17:20
Closing this issue because it is not a PandaSpigot issue, if you need help with plugin errors you can ask for help on our discord.

**Closed by uRyanxD** 2023-08-13 17:20 UTC
