### ISSUE TITLE
Hostile mobs don't spawn naturally

### ISSUE THREAD

**Issue by carechoripan** [hpfxd/PandaSpigot#154] opened 2023-07-13 19:21 UTC
well, previously i already installed this jar for my survival server 1.8 but i had to change it because i noticed that the hostile mobs didn't spawn at all, the animals worked normal but on the other hand it didn't even spawn a hostile mob. Before using pandaspigot I used normal spigot, which worked perfectly for me in terms of spawning mobs, here is the bukkit.yml file that I used with both .jar

https://pastes.dev/vNKAJed64L

**Comment by mechoriet** [comment] 2023-07-14 16:23
well this patch fixed issues with spigot's way to spawning mobs(ported from paper) https://github.com/hpfxd/PandaSpigot/blob/master/patches/server/0079-Fix-Bugs-with-Spigot-Mob-Spawn-Logic.patch

and your settings are like 20% of vanilla so very very rare mobs

![image](https://github.com/hpfxd/PandaSpigot/assets/4313219/6be3d88b-0d79-4635-b18b-efa4cdc93c96)
(source: https://paper-chan.moe/paper-optimization/#bukkit.yml)

tested this and a saw a few here and there but well it's very rare since your setting it to 20% in this instance

**Comment by MachineBreaker** [comment] 2023-07-15 14:06
Maybe there's a issue with the patch that changed light checks for creatures?

**Comment by uRyanxD** [comment] 2024-03-08 18:34
I couldn't reproduce it. Mobs spawn normally for me.

**Comment by uRyanxD** [comment] 2024-08-01 02:22
Should be fixed in 7cadf26

**Closed by uRyanxD** 2024-08-01 02:22 UTC
Labels: bug, cannot reproduce
