### ISSUE TITLE
Wrong order and white nickname of players in TAB

### ISSUE THREAD

**Issue by DrakMC** [hpfxd/PandaSpigot#12] opened 2022-06-01 21:52 UTC
When using the https://github.com/NEZNAMY/TAB plugin, some players have white nicknames and are incorrectly sorted. For NachoSpigot this works without a problem.

**Comment by hpfxd** [comment] 2022-06-01 22:00
Can you share your full list of plugins? I've been using TAB for months on multiple servers of mine using PandaSpigot and it works fine.

**Comment by DrakMC** [comment] 2022-06-14 00:01
PlaceholderAPI, spark, ViaVersion, HolographicDisplays, ProtocolLib, LuckPerms, SkinsRestorer, BungeeGuard, Intave, Vault, TAB

**Comment by FiveMJerry** [comment] 2022-11-08 20:27
Getting a similar issue with sorting not working properly via TAB. It works fine until the sorting type I has changes for the player then it does not update the list properly.

**Comment by jose27iwnl** [comment] 2024-08-13 22:18
Any feedback? @hpfxd or @uRyanxD  maybe close this?

**Comment by uRyanxD** [comment] 2024-09-01 18:20
I also cannot reproduce the problem, closing this issue

**Closed by uRyanxD** 2024-09-01 18:20 UTC
